apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ Values.namespace }}
  labels:
    app: nginx
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
